# -------------------------------------------------------------------- #
  useResourceCacheWhen = 'never'
# -------------------------------------------------------------------- #
  noJSConfigInAssets   = true
# -------------------------------------------------------------------- #
  cacheBusters         = [
  ]
# -------------------------------------------------------------------- #
  [buildStats]
# -------------------------------------------------------------------- #
  enable               = false
  disableTags          = false
  disableClasses       = false
  disableIDs           = false
# -------------------------------------------------------------------- #
