# -------------------------------------------------------------------- #
  confirm       = false
  dryRun        = false
  force         = false
# -------------------------------------------------------------------- #
  invalidateCDN = true
  maxDeletes    = 256
  workers       = 8
# -------------------------------------------------------------------- #
  target        = ''
# -------------------------------------------------------------------- #
  targets       = [
  ]
# -------------------------------------------------------------------- #
  matchers      = [
  ]
# -------------------------------------------------------------------- #
  orders        = [
  ]
# -------------------------------------------------------------------- #
