# -------------------------------------------------------------------- #
  date        = [
    'date',
  ]
# -------------------------------------------------------------------- #
  lastmod     = [
    'lastmod',
  ]
# -------------------------------------------------------------------- #
  publishDate = [
    'publishDate',
  ]
# -------------------------------------------------------------------- #
  expiryDate  = [
    'expiryDate',
  ]
# -------------------------------------------------------------------- #
