# -------------------------------------------------------------------- #
  respectCacheControlNoStoreInRequest  = true
  respectCacheControlNoStoreInResponse = true
# -------------------------------------------------------------------- #
  polls                                = [
  ]
# -------------------------------------------------------------------- #
  [cache.for]
# -------------------------------------------------------------------- #
  includes                             = [
  ]
  excludes                             = [
  ]
# -------------------------------------------------------------------- #
