# -------------------------------------------------------------------- #
  anchor         = 'smart'
  bgColor        = 'FFFFFF'
  resampleFilter = 'box'
# -------------------------------------------------------------------- #
  [meta]
# -------------------------------------------------------------------- #
  fields         = [
    '**',
  ]
  sources        = [
    'exif',
    'iptc',
  ]
# -------------------------------------------------------------------- #
  [avif]
# -------------------------------------------------------------------- #
  compression    = 'lossless'
  hint           = 'photo'
  quality        = 100
  encoderSpeed   = 10
# -------------------------------------------------------------------- #
  [jpeg]
# -------------------------------------------------------------------- #
  quality        = 100
# -------------------------------------------------------------------- #
  [webp]
# -------------------------------------------------------------------- #
  compression    = 'lossless'
  hint           = 'photo'
  quality        = 100
  method         = 6
  useSharpYuv    = true
# -------------------------------------------------------------------- #
