# -------------------------------------------------------------------- #
  label     = 'English'
  locale    = 'en'
  direction = 'ltr'
  weight    = 0
  disabled  = false
# -------------------------------------------------------------------- #
