# -------------------------------------------------------------------- #
  ['text/plain']
# -------------------------------------------------------------------- #
  delimiter = '.'
  suffixes  = [
    'txt',
  ]
# -------------------------------------------------------------------- #
  ['text/markdown']
# -------------------------------------------------------------------- #
  delimiter = '.'
  suffixes  = [
    'md',
    'markdown',
  ]
# -------------------------------------------------------------------- #
  ['text/rst']
# -------------------------------------------------------------------- #
  delimiter = '.'
  suffixes  = [
    'rst',
  ]
# -------------------------------------------------------------------- #
  ['text/asciidoc']
# -------------------------------------------------------------------- #
  delimiter = '.'
  suffixes  = [
    'adoc',
    'asciidoc',
  ]
# -------------------------------------------------------------------- #
  ['text/org']
# -------------------------------------------------------------------- #
  delimiter = '.'
  suffixes  = [
    'org',
  ]
# -------------------------------------------------------------------- #
  ['text/pandoc']
# -------------------------------------------------------------------- #
  delimiter = '.'
  suffixes  = [
    'pandoc',
  ]
# -------------------------------------------------------------------- #
  ['text/csv']
# -------------------------------------------------------------------- #
  delimiter = '.'
  suffixes  = [
    'csv',
  ]
# -------------------------------------------------------------------- #
  ['text/calendar']
# -------------------------------------------------------------------- #
  delimiter = '.'
  suffixes  = [
    'ics',
  ]
# -------------------------------------------------------------------- #
  ['text/html']
# -------------------------------------------------------------------- #
  delimiter = '.'
  suffixes  = [
    'html',
  ]
# -------------------------------------------------------------------- #
  ['text/x-gotmpl']
# -------------------------------------------------------------------- #
  delimiter = '.'
  suffixes  = [
    'gotmpl',
  ]
# -------------------------------------------------------------------- #
  ['text/css']
# -------------------------------------------------------------------- #
  delimiter = '.'
  suffixes  = [
    'css',
  ]
# -------------------------------------------------------------------- #
  ['text/x-sass']
# -------------------------------------------------------------------- #
  delimiter = '.'
  suffixes  = [
    'sass',
  ]
# -------------------------------------------------------------------- #
  ['text/x-scss']
# -------------------------------------------------------------------- #
  delimiter = '.'
  suffixes  = [
    'scss',
  ]
# -------------------------------------------------------------------- #
  ['text/javascript']
# -------------------------------------------------------------------- #
  delimiter = '.'
  suffixes  = [
    'js',
    'mjs',
    'cjs',
  ]
# -------------------------------------------------------------------- #
  ['text/jsx']
# -------------------------------------------------------------------- #
  delimiter = '.'
  suffixes  = [
    'jsx',
  ]
# -------------------------------------------------------------------- #
  ['text/typescript']
# -------------------------------------------------------------------- #
  delimiter = '.'
  suffixes  = [
    'ts',
  ]
# -------------------------------------------------------------------- #
  ['text/tsx']
# -------------------------------------------------------------------- #
  delimiter = '.'
  suffixes  = [
    'tsx',
  ]
# -------------------------------------------------------------------- #
  ['application/toml']
# -------------------------------------------------------------------- #
  delimiter = '.'
  suffixes  = [
    'toml',
  ]
# -------------------------------------------------------------------- #
  ['application/yaml']
# -------------------------------------------------------------------- #
  delimiter = '.'
  suffixes  = [
    'yaml',
  ]
# -------------------------------------------------------------------- #
  ['application/xml']
# -------------------------------------------------------------------- #
  delimiter = '.'
  suffixes  = [
    'xml',
  ]
# -------------------------------------------------------------------- #
  ['application/rss+xml']
# -------------------------------------------------------------------- #
  delimiter = '.'
  suffixes  = [
    'rss',
    'xml',
  ]
# -------------------------------------------------------------------- #
  ['application/atom+xml']
# -------------------------------------------------------------------- #
  delimiter = '.'
  suffixes  = [
    'atom',
    'xml',
  ]
# -------------------------------------------------------------------- #
  ['application/json']
# -------------------------------------------------------------------- #
  delimiter = '.'
  suffixes  = [
    'json',
  ]
# -------------------------------------------------------------------- #
  ['application/manifest+json']
# -------------------------------------------------------------------- #
  delimiter = '.'
  suffixes  = [
    'webmanifest',
  ]
# -------------------------------------------------------------------- #
  ['application/pdf']
# -------------------------------------------------------------------- #
  delimiter = '.'
  suffixes  = [
    'pdf',
  ]
# -------------------------------------------------------------------- #
  ['application/wasm']
# -------------------------------------------------------------------- #
  delimiter = '.'
  suffixes  = [
    'wasm',
  ]
# -------------------------------------------------------------------- #
  ['application/octet-stream']
# -------------------------------------------------------------------- #
  delimiter = '.'
  suffixes  = [
  ]
# -------------------------------------------------------------------- #
  ['font/ttf']
# -------------------------------------------------------------------- #
  delimiter = '.'
  suffixes  = [
    'ttf',
  ]
# -------------------------------------------------------------------- #
  ['font/otf']
# -------------------------------------------------------------------- #
  delimiter = '.'
  suffixes  = [
    'otf',
  ]
# -------------------------------------------------------------------- #
  ['image/bmp']
# -------------------------------------------------------------------- #
  delimiter = '.'
  suffixes  = [
    'bmp',
  ]
# -------------------------------------------------------------------- #
  ['image/tiff']
# -------------------------------------------------------------------- #
  delimiter = '.'
  suffixes  = [
    'tiff',
  ]
# -------------------------------------------------------------------- #
  ['image/jpeg']
# -------------------------------------------------------------------- #
  delimiter = '.'
  suffixes  = [
    'jpeg',
    'jfif',
  ]
# -------------------------------------------------------------------- #
  ['image/png']
# -------------------------------------------------------------------- #
  delimiter = '.'
  suffixes  = [
    'png',
  ]
# -------------------------------------------------------------------- #
  ['image/gif']
# -------------------------------------------------------------------- #
  delimiter = '.'
  suffixes  = [
    'gif',
  ]
# -------------------------------------------------------------------- #
  ['image/heif']
# -------------------------------------------------------------------- #
  delimiter = '.'
  suffixes  = [
    'heif',
  ]
# -------------------------------------------------------------------- #
  ['image/heic']
# -------------------------------------------------------------------- #
  delimiter = '.'
  suffixes  = [
    'heic',
  ]
# -------------------------------------------------------------------- #
  ['image/webp']
# -------------------------------------------------------------------- #
  delimiter = '.'
  suffixes  = [
    'webp',
  ]
# -------------------------------------------------------------------- #
  ['image/avif']
# -------------------------------------------------------------------- #
  delimiter = '.'
  suffixes  = [
    'avif',
  ]
# -------------------------------------------------------------------- #
  ['image/svg+xml']
# -------------------------------------------------------------------- #
  delimiter = '.'
  suffixes  = [
    'svg',
  ]
# -------------------------------------------------------------------- #
  ['video/3gpp']
# -------------------------------------------------------------------- #
  delimiter = '.'
  suffixes  = [
    '3gpp',
  ]
# -------------------------------------------------------------------- #
  ['video/x-msvideo']
# -------------------------------------------------------------------- #
  delimiter = '.'
  suffixes  = [
    'avi',
  ]
# -------------------------------------------------------------------- #
  ['video/mpeg']
# -------------------------------------------------------------------- #
  delimiter = '.'
  suffixes  = [
    'mpeg',
  ]
# -------------------------------------------------------------------- #
  ['video/mp4']
# -------------------------------------------------------------------- #
  delimiter = '.'
  suffixes  = [
    'mp4',
  ]
# -------------------------------------------------------------------- #
  ['video/ogg']
# -------------------------------------------------------------------- #
  delimiter = '.'
  suffixes  = [
    'ogv',
  ]
# -------------------------------------------------------------------- #
  ['video/webm']
# -------------------------------------------------------------------- #
  delimiter = '.'
  suffixes  = [
    'webm',
  ]
# -------------------------------------------------------------------- #
