# -------------------------------------------------------------------- #
  disableHTML           = false
  disableCSS            = false
  disableJS             = false
  disableJSON           = false
  disableXML            = false
  disableSVG            = false
# -------------------------------------------------------------------- #
  [tdewolff.html]
# -------------------------------------------------------------------- #
  keepWhiteSpace        = true
  keepComments          = true
  keepSpecialComments   = true
  keepDocumentTags      = true
  keepEndTags           = true
  keepDefaultAttrValues = true
  keepQuotes            = true
  templateDelims        = [ '', '' ]
# -------------------------------------------------------------------- #
  [tdewolff.css]
# -------------------------------------------------------------------- #
  version               = 0
  precision             = 0
# -------------------------------------------------------------------- #
  [tdewolff.js]
# -------------------------------------------------------------------- #
  version               = 0
  precision             = 0
  keepVarNames          = true
# -------------------------------------------------------------------- #
  [tdewolff.json]
# -------------------------------------------------------------------- #
  keepNumbers           = true
  precision             = 0
# -------------------------------------------------------------------- #
  [tdewolff.xml]
# -------------------------------------------------------------------- #
  keepWhitespace        = true
# -------------------------------------------------------------------- #
  [tdewolff.svg]
# -------------------------------------------------------------------- #
  precision             = 0
  keepComments          = true
  keepNamespaces        = [
  ]
# -------------------------------------------------------------------- #
