# -------------------------------------------------------------------- #
  workspace         = 'off'
  auth              = ''
  proxy             = 'direct'
  venderClosest     = false
  noProxy           = '*.*'
  noVendor          = '*.*'
  private           = '*.*'
# -------------------------------------------------------------------- #
  replacements      = [
  ]
# -------------------------------------------------------------------- #
  imports           = [
  ]
# -------------------------------------------------------------------- #
  [hugoVersion]
# -------------------------------------------------------------------- #
  extended          = false
  min               = ''
  max               = ''
# -------------------------------------------------------------------- #
  [[mounts]]
# -------------------------------------------------------------------- #
  source            = 'archetypes'
  target            = 'archetypes'
  disableWatch      = false
  sites.complements = {}
  sites.matrix      = {}
  files             = [
  ]
# -------------------------------------------------------------------- #
  [[mounts]]
# -------------------------------------------------------------------- #
  source            = 'assets'
  target            = 'assets'
  disableWatch      = false
  sites.complements = {}
  sites.matrix      = {}
  files             = [
  ]
# -------------------------------------------------------------------- #
  [[mounts]]
# -------------------------------------------------------------------- #
  source            = 'content'
  target            = 'content'
  disableWatch      = false
  sites.complements = {}
  sites.matrix      = {}
  files             = [
  ]
# -------------------------------------------------------------------- #
  [[mounts]]
# -------------------------------------------------------------------- #
  source            = 'data'
  target            = 'data'
  disableWatch      = false
  sites.complements = {}
  sites.matrix      = {}
  files             = [
  ]
# -------------------------------------------------------------------- #
  [[mounts]]
# -------------------------------------------------------------------- #
  source            = 'i18n'
  target            = 'i18n'
  disableWatch      = false
  sites.complements = {}
  sites.matrix      = {}
  files             = [
  ]
# -------------------------------------------------------------------- #
  [[mounts]]
# -------------------------------------------------------------------- #
  source            = 'layouts'
  target            = 'layouts'
  disableWatch      = false
  sites.complements = {}
  sites.matrix      = {}
  files             = [
  ]
# -------------------------------------------------------------------- #
  [[mounts]]
# -------------------------------------------------------------------- #
  source            = 'static'
  target            = 'static'
  disableWatch      = false
  sites.complements = {}
  sites.matrix      = {}
  files             = [
  ]
# -------------------------------------------------------------------- #
