# -------------------------------------------------------------------- #
  application-name  = 'FWC26'
# -------------------------------------------------------------------- #
  authors           = [
    'ibrahim Haras',
  ]
# -------------------------------------------------------------------- #
  generators        = [
    'Hugo',
  ]
# -------------------------------------------------------------------- #
