# -------------------------------------------------------------------- #
  [googleAnalytics]
# -------------------------------------------------------------------- #
  disable           = true
  respectDoNotTrack = true
# -------------------------------------------------------------------- #
  [disqus]
# -------------------------------------------------------------------- #
  disable           = true
# -------------------------------------------------------------------- #
  [instagram]
# -------------------------------------------------------------------- #
  disable           = true
  simple            = true
# -------------------------------------------------------------------- #
  [x]
# -------------------------------------------------------------------- #
  disable           = true
  simple            = true
  enableDNT         = true
# -------------------------------------------------------------------- #
  [vimeo]
# -------------------------------------------------------------------- #
  disable           = true
  simple            = true
  enableDNT         = true
# -------------------------------------------------------------------- #
  [youtube]
# -------------------------------------------------------------------- #
  disable           = true
  privacyEnhanced   = true
# -------------------------------------------------------------------- #
