# -------------------------------------------------------------------- #
  threshold            = 80
  toLower              = true
  includeNewer         = true
# -------------------------------------------------------------------- #
  [[indices]]
# -------------------------------------------------------------------- #
  name                 = 'keywords'
  type                 = 'basic'
  applyFilter          = false
  weight               = 0
  cardinalityThreshold = 0
  pattern              = ''
  toLower              = true
# -------------------------------------------------------------------- #
  [[indices]]
# -------------------------------------------------------------------- #
  name                 = 'tags'
  type                 = 'basic'
  applyFilter          = false
  weight               = 0
  cardinalityThreshold = 0
  pattern              = ''
  toLower              = true
# -------------------------------------------------------------------- #
