# -------------------------------------------------------------------- #
  enableInlineShortcodes = false
  allowContent           = [
    'text/html',
  ]
# -------------------------------------------------------------------- #
  [exec]
# -------------------------------------------------------------------- #
  allow                  = [
  ]
  osenv                  = [
  ]
# -------------------------------------------------------------------- #
  [funcs]
# -------------------------------------------------------------------- #
  getenv                 = [
  ]
# -------------------------------------------------------------------- #
  [http]
# -------------------------------------------------------------------- #
  methods                = [
  ]
  urls                   = [
  ]
  mediaTypes             = [
  ]
# -------------------------------------------------------------------- #
  [node.permissions]
# -------------------------------------------------------------------- #
  disable                = true
  allowRead              = [
  ]
  allowWrite             = [
  ]
  allowAddons            = [
  ]
  allowWorker            = [
  ]
  allowChildProcess      = [
  ]
# -------------------------------------------------------------------- #
