# -------------------------------------------------------------------- #
  [rss]
# -------------------------------------------------------------------- #
  limit            = -1
# -------------------------------------------------------------------- #
  [googleAnalytics]
# -------------------------------------------------------------------- #
  id               = ''
# -------------------------------------------------------------------- #
  [disqus]
# -------------------------------------------------------------------- #
  shortname        = ''
# -------------------------------------------------------------------- #
  [x]
# -------------------------------------------------------------------- #
  disableInlineCSS = true
# -------------------------------------------------------------------- #
